#ifndef PRESET_CONFIG_H
#define PRESET_CONFIG_H

#define PRESET_VERSION_MAJOR 1
#define PRESET_VERSION_MICRO 0
#define PRESET_VERSION_MINOR 1

#define STRING(__A) #__A

#define CONVERT_VERSION(major, micro, minor) STRING(major) "." STRING(micro) "." STRING(minor)

#define PRESET_VERSION CONVERT_VERSION(PRESET_VERSION_MAJOR, \
  PRESET_VERSION_MICRO, PRESET_VERSION_MINOR)

#define GLOBAL_USERNAME "dbc"

#endif  //PRESET_CONFIG_H
